### PR TITLE
Remove GNU parallel dependency

### PR DESCRIPTION
**Pull request by semenko**
Use bash builtins instead of GNU parallel.

This is slightly faster than the parallel implementation.

Output identical, compared with `diff -bur ../biscuit-qc/ ../biscuit-qc-patch-1/`

### CODE REVIEW

**Comment by semenko** [comment]
Hey @jamorrison is it useful for me to updated this — or should I close this PR?

(Don't see a good reason to use parallel at all here.)

**Comment by jamorrison** [comment]
@semenko I think this was a good update. I noticed this after I started the release process for BISCUIT v1.2.0 though, so it'll go into the next release of BISCUIT. Thanks for the PR!

**Comment by semenko** [comment]
Thanks! Does this latest version (1.2.0) auto-push to bioconda? (Exciting changes!)

**Comment by jamorrison** [comment]
I have a PR in testing for bioconda at the moment. Should be available in a day or two, review and approval dependent.

**Comment by bounlu** [comment]
Hi,

I am curious to know why bash builtin background processing should be faster than `GNU parallel`?

If not slower, I would still go with GNU parallel as it has better capabilities and handling with parallel execution although this is not very much applicable in this case.

**Comment by semenko** [comment]
For a few reasons, `parallel` was forcing extra work. For example this:

https://github.com/huishenlab/biscuit/pull/33/files#diff-03f6544f78af96f7e16c293b67a23d876cd5a1d585d61658675c2b282a6c552dL136
image

`parallel` was running `samtools view`, then we running it **again** multiple times for quality filters (and other options) not implemented by `bedtools` commands.

Plus no need for extra dependencies :P

**Pull request merged**
